# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CreateAPK
on:
  pull_request:
    branches: [ "**" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - id: shouldrun
        run: |
          if [[ "${{ github.head_ref }}" == *"test"* ]]; then
              echo "shouldrun=false" >> $GITHUB_OUTPUT
          else
              echo "shouldrun=true" >> $GITHUB_OUTPUT 
          fi

      - run: echo ${{ needs.setup.outputs.shouldrun }}
