on:
  pull_request:
      
jobs:
    setup:
      runs-on: ubuntu-latest
      outputs:
       output1: ${{ steps.shouldrun.outputs.shouldrun }}
      steps:
        - id: shouldrun
          run: |
            if [[ "${{ github.head_ref }}" == "dsafarik-cen89982-patch-1" ]]; then
                echo "shouldrun=false" >> $GITHUB_OUTPUT
            else
                echo "shouldrun=true" >> $GITHUB_OUTPUT 
            fi
            
    is_valid:
      runs-on: ubuntu-latest
      needs: [setup]
      steps:
        # Checkout code
        - name: Checkout code
          uses: actions/checkout@v3
        - run: echo ${{ needs.setup.outputs.output1 }}
