# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CreateAPK
on:
  pull_request:
    branches: [ "**" ]

jobs:
   setup:
     runs-on: ubuntu-latest
     outputs:
      output1: ${{ steps.setup.outputs.shouldrun }}
     steps:
       - id: shouldrun
         run: |
           if [[ "${{ github.head_ref }}" == *"test"* ]]; then
               echo "shouldrun=false" >> $GITHUB_OUTPUT
           else
               echo "shouldrun=true" >> $GITHUB_OUTPUT 
           fi
           
   is_valid:
     runs-on: ubuntu-latest
     needs: [setup]
     steps:
      - env:
          OUTPUT1: ${{ needs.setup.outputs.output1 }}
        run: echo "$OUTPUT1"
