name: Build project

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 15
    permissions:
      contents: read

    steps:      
    # SETUP
    - uses: actions/checkout@v4
      with:
         fetch-depth: 0
         
    # BUILD
    - name: Build
      if: ${{ github.ref_type != 'tag' }}
      run: xcodebuild clean -project "George Town.xcodeproj" -scheme "George Town" -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=latest"
      
     # TEST
#    - name: Run Unit Tests
#      if: ${{ github.ref_type != 'tag' }}
#      run: xcodebuild test -project "George Town.xcodeproj" -scheme "George Town" -destination "platform=iOS Simulator,name=iPhone 14 Pro,OS=latest"
